
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username:
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: faleconosco_netza_development

test:
  <<: *default
  database: faleconosco_netza_test

production:
  <<: *default
  database: faleconosco_netza_production
  username: faleconosco_netza
  password: <%= ENV['FALECONOSCO_NETZA_DATABASE_PASSWORD'] %>
